gadget:
  auto_detect_mode: true
  enabled: true
  num_ports: 10
general:
  default_preset: default
  hotplug_poll_interval: 2.0
  log_level: INFO
hardware:
  enabled: true
  uart_chips:
  - address: 72
    channels: 2
  - address: 73
    channels: 2
platform: auto
web_ui:
  enabled: true
  host: 0.0.0.0
  midi_log_max: 500
  port: 8080
wifi_ap:
  channel: 6
  ip: 192.168.4.1
  password: '1231232132132'
  ssid: MIDI-BOX
